# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            MPI Tutorial
tagline:
url:              http://mpitutorial.com
paginate:         1
baseurl:          http://wesleykendall.github.io/mpitutorial
author:
  name:           Wes Kendall
  url:            https://github.com/wesleykendall/
  email:          wesleykendall@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/wesleykendall/mpitutorial/
pages_list:       
  About: '{{ site.baseurl }}about'
